"""Rebuild the studio gallery from published case-study HTML metadata."""
from pathlib import Path
from html.parser import HTMLParser
import json,re
root=Path(__file__).resolve().parents[1]
class Images(HTMLParser):
 def __init__(self):super().__init__();self.images=[]
 def handle_starttag(self,tag,attrs):
  a=dict(attrs)
  if tag=='img' and a.get('src','').startswith('assets/imgs/projects/'):
   self.images.append({'src':a['src'],'alt':a.get('alt','')})
projects=[]
for path in sorted(root.glob('project-*.html')):
 text=path.read_text();work=None
 for raw in re.findall(r'<script type="application/ld\+json">(.*?)</script>',text,re.S):
  data=json.loads(raw)
  if data.get('@type')=='CreativeWork':work=data
 if not work:continue
 parser=Images();parser.feed(text);images=[]
 for image in parser.images:
  if not (root/image['src']).is_file():raise SystemExit('Missing image: '+image['src'])
  if image['src'] not in [x['src'] for x in images]:images.append(image)
 if not images:continue
 projects.append({'title':work.get('about',{}).get('name',work['name']),'href':path.name,'images':images})
(root/'assets/js/case-studies.js').write_text('// Generated by scripts/sync-case-studies.py. Update the case study, then regenerate.\nwindow.SANTI_CASE_STUDIES = '+json.dumps(projects,ensure_ascii=False,indent=2)+';\n')
print('Synced',len(projects),'case studies and',sum(len(p['images']) for p in projects),'images.')
